### PR TITLE
compatibility with dynamic assemblies and different namespace/class conditions

### LINKED ISSUE #231: [BUG] Dynamic Assemblies like URP make asset based generator to throw exceptions [BUG]
**Describe the bug**
When the Asset based generator's type dropdown makes an lookup for serialized types it throws exceptions on dynamic assemblies. the URP assembly seems to be dynamic

**To Reproduce**
add Univseral RP via package manage, try to select a type in the asset based generator

### PR DESCRIPTION
**Pull request by soraphis**
fixes #231 #232 #233

### CODE REVIEW

**Comment by Casey-Hofland** [comment]
The fix didn't work for me, but I've found the issue (it's a doozy). URP has a class Readme, with a nested class Section. This type's Namespace is null, causing the generators query to fail.

Ignoring anything with a null namespace is not an option, as the InputSystem package relies on nested types being supported by the generator.

**Review by Casey-Hofland — CHANGES_REQUESTED** [review]
This prevents the generator from crashing, but generating a nested types doesn't work.

e.g.
[Serializable] public class Foo
{
    [Serializable] public class Bar {}
}

will generate
public sealed class BarConstant : AtomBaseVariable<Bar> (should be BarConstant : AtomBaseVariable<Foo.Bar>)

BarConstant should maybe get a different name, as it might conflict with existing generated classes. Foo_BarConstant would be the safest, although slightly awkward. We can discuss this later.

Please test generating a nested type and request a review upon a test without any errors.

**Comment by soraphis** [comment]
corrected an error in my previous fix for no-namespace classes.
corrected generation for nested classes

**Review by Casey-Hofland — CHANGES_REQUESTED** [review]
Generator not working

Can you please test generating Again with this script and ask for a review only after you can successfully generate it without any errors?
[Something.txt](https://github.com/AdamRamberg/unity-atoms/files/5761752/Something.txt)

**Review by Casey-Hofland — COMMENTED** [review]
Please read my commit messages and ask me questions if they are uninterpretable (some I wrote kinda quick).

**Review by miikalo — APPROVED** [review]

**Pull request merged**
